[package]
name = "polkadot-rpc"
version = "0.7.5"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
client = { package = "sc-client", git = "https://github.com/mxinden/substrate", branch = "sentry-nodes-flag-polkadot-master" }
jsonrpc-core = "14.0.3"
polkadot-primitives = { path = "../primitives" }
sp-runtime = { git = "https://github.com/mxinden/substrate", branch = "sentry-nodes-flag-polkadot-master"  }
sc-rpc = { git = "https://github.com/mxinden/substrate", branch = "sentry-nodes-flag-polkadot-master" }
txpool-api = { package = "sp-transaction-pool-api", git = "https://github.com/mxinden/substrate", branch = "sentry-nodes-flag-polkadot-master" }
frame-rpc-system = { package = "substrate-frame-rpc-system", git = "https://github.com/mxinden/substrate", branch = "sentry-nodes-flag-polkadot-master"  }
pallet-transaction-payment-rpc = { git = "https://github.com/mxinden/substrate", branch = "sentry-nodes-flag-polkadot-master" }
polkadot-runtime = { path = "../runtime" }

